# Site settings
title: Iterations
email: s@l.co
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yuanhangw.github.com" # the base hostname & protocol for your site
twitter_username: .
github_username:  .

# Build settings
markdown: kramdown
